name: tensorflow
channels:
  - defaults
dependencies:
  - _tflow_select=2.3.0
  - absl-py=0.6.1
  - astor=0.7.1
  - backcall=0.1.0
  - blas=1.0
  - bzip2=1.0.6
  - c-ares=1.15.0
  - ca-certificates=2018.03.07
  - cairo=1.14.12
  - certifi=2018.11.29
  - decorator=4.3.0
  - ffmpeg=4.0
  - fontconfig=2.13.0
  - freeglut=3.0.0
  - freetype=2.9.1
  - gast=0.2.0
  - glib=2.56.2
  - graphite2=1.3.12
  - grpcio=1.16.0
  - h5py=2.8.0
  - harfbuzz=1.8.8
  - hdf5=1.10.2
  - icu=58.2
  - intel-openmp=2019.0
  - ipython=7.2.0
  - ipython_genutils=0.2.0
  - jasper=2.0.14
  - jedi=0.13.2
  - jpeg=9b
  - keras=2.2.4
  - keras-applications=1.0.6
  - keras-base=2.2.4
  - keras-preprocessing=1.0.5
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgcc-ng=8.2.0
  - libgfortran-ng=7.3.0
  - libglu=9.0.0
  - libopencv=3.4.2
  - libopus=1.3
  - libpng=1.6.35
  - libprotobuf=3.6.1
  - libstdcxx-ng=8.2.0
  - libtiff=4.0.9
  - libuuid=1.0.3
  - libvpx=1.7.0
  - libxcb=1.13
  - libxml2=2.9.8
  - markdown=3.0.1
  - mkl=2018.0.3
  - mkl_fft=1.0.6
  - mkl_random=1.0.1
  - ncurses=6.1
  - numpy=1.15.4
  - numpy-base=1.15.4
  - opencv=3.4.2
  - openssl=1.1.1
  - parso=0.3.1
  - pcre=8.42
  - pexpect=4.6.0
  - pickleshare=0.7.5
  - pip=18.1
  - pixman=0.34.0
  - prompt_toolkit=2.0.7
  - protobuf=3.6.1
  - ptyprocess=0.6.0
  - py-opencv=3.4.2
  - pygments=2.3.1
  - python=3.6.7
  - pyyaml=3.13
  - readline=7.0
  - scipy=1.1.0
  - setuptools=40.5.0
  - six=1.11.0
  - sqlite=3.25.3
  - tensorboard=1.12.0
  - tensorflow=1.12.0
  - tensorflow-base=1.12.0
  - termcolor=1.1.0
  - tk=8.6.8
  - traitlets=4.3.2
  - wcwidth=0.1.7
  - werkzeug=0.14.1
  - wheel=0.32.2
  - xz=5.2.4
  - yaml=0.1.7
  - zlib=1.2.11
  - pip:
    - cycler==0.10.0
    - kiwisolver==1.0.1
    - matplotlib==3.0.2
    - pandas==0.23.4
    - pyparsing==2.3.0
    - python-dateutil==2.7.5
    - pytz==2018.7

